### ISSUE TITLE
InvalidAlgorithm

### ISSUE THREAD

**Issue by 1Euro7Cent** [danielepiccone/ditherjs#10]
I've made the example stuff 
![image](https://user-images.githubusercontent.com/67194495/112637210-34ce8b80-8e3e-11eb-9e38-dfb53f2c4806.png)

the color array: 
![image](https://user-images.githubusercontent.com/67194495/112636769-d0133100-8e3d-11eb-997d-772119cf0b9f.png)
err:
![image](https://user-images.githubusercontent.com/67194495/112636803-d9040280-8e3d-11eb-92ef-c0224f03ea9f.png)

additional information: 
windows 10 pro 64bit

node: v14.16.0
npm: 6.14.11

Did I make anything wrong?

**Comment by bogstandard** [comment]
Had this issue too, it looks like the documentation is incorrect and the options should be given in the following way:

```

const options = {
    "step": 1, // The step for the pixel quantization n = 1,2,3...
    //"palette": defaultPalette, // an array of colors as rgb arrays
    "algorithm": "diffusion" // one of ["ordered", "diffusion", "atkinson"]
};

const ditherjs = new DitherJS(options);
ditherjs.dither('img', options); // should target <img> elements
```

**Comment by 1Euro7Cent** [comment]
I already fixed it by looking into the source code. I forgot about this issue existing. But thank you.
